[shell]
program = "/Users/qoidnaufal/.cargo/bin/nu"
args = ["-l"]
# args = ["-e", "zellij"]

[scrolling]
history = 10000
multiplier = 3

[colors]
transparent_background_colors = true

[window]
decorations = "Buttonless"
padding = { x = 3, y = 5 }
opacity = 0.75
# blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
