"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "default"
format = """

$status\
$directory\
$git_branch\
$cmd_duration\
$character\
"""
# $git_status\

[palettes.default]
prompt_ok  = "#8047c1"
prompt_err = "#e23140"
icon       = "#161514"
separator  = "#35312c"
bg0        = "#504945"
fg0        = "#e9f42d"

directory  = "#9f31e2"
duration   = "#e26f31"
status     = "#e23140"
git_branch = "#31e268"
git_status = "#31e268"

[character]
success_symbol = "[ ❯](fg:prompt_ok)"
error_symbol = "[ ❯](fg:prompt_err)"

[status]
# format = "[](fg:status)[](fg:icon bg:status)[](fg:status bg:bg0)[ $status](bg:bg0)[](fg:bg0)[─](fg:separator)"
format = "[](fg:status)[](fg:icon bg:status)[](fg:status bg:bg0)[ $status](bg:bg0)[](fg:bg0)[ ](fg:separator)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
# pipestatus_format = "(fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:bg0)[ $pipestatus](bg:bg0)[](fg:bg0)[─](fg:separator)"
pipestatus_format = "(fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:bg0)[ $pipestatus](bg:bg0)[](fg:bg0)[ ](fg:separator)"
disabled = false

[directory]
format = "[](fg:directory)[](fg:icon bg:directory)[](fg:directory bg:bg0)[ $path](bg:bg0 fg:fg0)[](fg:bg0)"
truncate_to_repo = true
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Repos" = "󰲋"

[git_branch]
# format = "[─](fg:separator)[](fg:git_branch)[](fg:icon bg:git_branch)[](fg:git_branch bg:bg0)[ $branch](bg:bg0 fg:fg0)"
format = "[ ](fg:separator)[](fg:git_branch)[](fg:icon bg:git_branch)[](fg:git_branch bg:bg0)[ $branch](bg:bg0 fg:fg0)[](fg:bg0)"

[git_status]
format = "[](fg:bg0 bg:git_status)[$all_status$ahead_behind](fg:icon bg:git_status)[](fg:git_status)"

[cmd_duration]
# format = "[─](fg:separator)[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:bg0)[ $duration](bg:bg0 fg:fg0)[](fg:bg0)"
format = "[ ](fg:separator)[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:bg0)[ $duration](bg:bg0 fg:fg0)[](fg:bg0)"
min_time = 1000
