theme = "gruvbox_edit"

[editor]
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"
true-color = true
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-signature-help-docs = false
display-inlay-hints = false

[editor.whitespace]
render = "none"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
# "A-L" = "goto_next_buffer"
# "A-H" = "goto_previous_buffer"
"C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-l" = ["delete_selection", "paste_after"]
"C-h" = ["delete_selection", "move_char_left", "paste_before"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
# "A-L" = "goto_next_buffer"
# "A-H" = "goto_previous_buffer"
"C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"C-l" = ["delete_selection", "paste_after"]
"C-h" = ["delete_selection", "move_char_left", "paste_before"]
